const params=new URLSearchParams(location.search),token=params.get('token'),form=document.getElementById('activation-form'),err=document.getElementById('activation-error'),UI=window.VeraUI,installStep=document.getElementById('install-step'),installButton=document.getElementById('install-pwa'),installedContinue=document.getElementById('installed-continue'),iosHelp=document.getElementById('ios-install-help'),manualHelp=document.getElementById('manual-install-help'),progressInstall=document.getElementById('progress-install'),progressPin=document.getElementById('progress-pin');
let deferredInstall=null,tokenInfo=null,manualHelpTimer=null;

async function api(u,o={}){const r=await fetch(u,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...o});if(!r.ok){let m=`Error ${r.status}`;try{m=(await r.json()).detail||m}catch{}throw new Error(m)}return r.json()}
function standalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function setInstallButtonLabel(label){installButton.innerHTML=`<span data-fa="user-plus"></span> ${label}`;UI.decorateIcons(installButton)}
function fail(m){document.getElementById('activation-title').innerHTML='QR <span>no válido</span>';document.getElementById('activation-copy').textContent='No se pudo validar este enlace temporal.';err.textContent=m;installStep.classList.add('hidden');form.classList.add('hidden');UI.notify(m,'error',{title:'No se pudo validar el QR'})}
function showPin(){if(manualHelpTimer){clearTimeout(manualHelpTimer);manualHelpTimer=null}installStep.classList.add('hidden');form.classList.remove('hidden');progressInstall.classList.remove('active');progressPin.classList.add('active');document.getElementById('activation-title').innerHTML='Configurá tu <span>PIN</span>';document.getElementById('activation-copy').textContent=`${tokenInfo.full_name}: creá y confirmá tu PIN de 4 dígitos para terminar la activación.`;UI.decorateIcons(document)}
function showInstall(){form.classList.add('hidden');installStep.classList.remove('hidden');progressInstall.classList.add('active');progressPin.classList.remove('active');iosHelp.classList.add('hidden');manualHelp.classList.add('hidden');installedContinue.classList.add('hidden');installButton.disabled=false;document.getElementById('activation-title').innerHTML='Instalá <span>VERA</span>';document.getElementById('activation-copy').textContent=`${tokenInfo.full_name}: primero instalá VERA en este teléfono. Después configuraremos tu PIN.`;if(isIOS()){setInstallButtonLabel('Cómo instalar VERA');iosHelp.classList.remove('hidden');installedContinue.classList.remove('hidden')}else{setInstallButtonLabel('Instalar VERA');manualHelpTimer=setTimeout(()=>{if(!deferredInstall&&!standalone()&&!installStep.classList.contains('hidden')){manualHelp.classList.remove('hidden');installedContinue.classList.remove('hidden')}},1800)}UI.decorateIcons(document)}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;if(manualHelpTimer){clearTimeout(manualHelpTimer);manualHelpTimer=null}if(tokenInfo&&!standalone()){installButton.disabled=false;manualHelp.classList.add('hidden');setInstallButtonLabel('Instalar VERA')}});
window.addEventListener('appinstalled',()=>{deferredInstall=null;UI.notify('VERA quedó instalada en el teléfono.','success',{title:'Instalación completada'});showPin()});

installButton.addEventListener('click',async()=>{if(standalone()){showPin();return}if(deferredInstall){const prompt=deferredInstall;deferredInstall=null;await prompt.prompt();const result=await prompt.userChoice;if(result.outcome==='accepted'){UI.notify('Instalación aceptada. Terminá la instalación y configurá tu PIN.','success');setTimeout(()=>showPin(),500)}else{manualHelp.classList.remove('hidden');installedContinue.classList.remove('hidden')}return}if(isIOS()){iosHelp.classList.remove('hidden')}else{manualHelp.classList.remove('hidden')}installedContinue.classList.remove('hidden')});
installedContinue.addEventListener('click',showPin);

async function init(){if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('/sw.js');await navigator.serviceWorker.ready}catch{UI.notify('No se pudo preparar la instalación PWA.','warning')}}if(!token){fail('Falta el token del QR.');return}const loading=UI.notify('Validando enlace temporal...','loading');try{tokenInfo=await api(`/api/access/${encodeURIComponent(token)}`);const labels={activation:'Activación inicial',pin_reset:'Restablecer PIN',relink:'Revincular VERA'};document.getElementById('activation-purpose').textContent=labels[tokenInfo.purpose]||'Acceso VERA';if(tokenInfo.purpose==='pin_reset'||standalone())showPin();else showInstall()}catch(e){fail(e.message)}finally{loading.close()}}

form.addEventListener('submit',async e=>{e.preventDefault();err.textContent='';const b=e.submitter;UI.setBusy(b,true,'Guardando...');try{const result=await api(`/api/access/${encodeURIComponent(token)}/complete`,{method:'POST',body:JSON.stringify({pin:document.getElementById('new-pin').value,pin_confirm:document.getElementById('confirm-pin').value})});form.classList.add('hidden');document.getElementById('activation-title').innerHTML='VERA <span>activada</span>';document.getElementById('activation-copy').textContent='Tu dispositivo y tu PIN quedaron vinculados. Ya podés entrar a tu aplicativo.';document.getElementById('go-login').classList.remove('hidden');UI.notify('Activación completada correctamente.','success');setTimeout(()=>location.replace(result.redirect||'/cliente'),900)}catch(x){err.textContent=x.message;UI.notify(x.message,'error',{title:'No se pudo completar la activación'})}finally{UI.setBusy(b,false)}});

init();
