const state={me:null,vehicle:null,services:[],deferredInstall:null};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const UI=window.VeraUI;
const icon=(name,cls='')=>UI?.icon(name,cls)||'';
const devClient=new URLSearchParams(location.search).get('client');
async function api(url,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(devClient)headers['X-VERA-DEV-CLIENT']=devClient;const r=await fetch(url,{credentials:'same-origin',headers,...options});if(!r.ok){let m=`Error ${r.status}`;try{m=(await r.json()).detail||m}catch{}const e=new Error(m);e.status=r.status;throw e}return r.status===204?null:r.json()}
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function fmtDate(v){if(!v)return'—';const x=new Date(`${v}T00:00:00`);return Number.isNaN(x.getTime())?esc(v):new Intl.DateTimeFormat('es-AR').format(x)}
function fmtDateTime(v){if(!v)return'—';const x=new Date(v);return Number.isNaN(x.getTime())?esc(v):new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(x)}
const km=v=>v===null||v===undefined?'—':`${Number(v).toLocaleString('es-AR')} km`;
function showMain(){$('#login-view').classList.remove('active');$('#app-view').classList.add('active');showView('vehicles');UI.decorateIcons(document)}
function showLogin(){$('#app-view').classList.remove('active');$('#login-view').classList.add('active');$('#client-pin').value=''}
function showView(name){if(['vehicle','history','detail'].includes(name)&&!state.vehicle)name='vehicles';$$('[data-view]').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('.client-nav [data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===name));window.scrollTo({top:0,behavior:'auto'});UI.decorateIcons(document)}
async function loadMe(){state.me=await api('/api/client/me');$('#client-greeting').textContent=`${state.me.full_name} · ${state.me.phone}`;$('#message-badge').textContent=state.me.unread_messages||0;renderVehicles()}
function renderVehicles(){const h=$('#vehicle-list'),vs=state.me?.vehicles||[];if(!vs.length){h.innerHTML=`<div class="notice">${icon('circle-info')} No hay vehículos asociados a esta cuenta.</div>`;return}h.innerHTML=vs.map(v=>`<button class="vehicle-card" type="button" data-vehicle-id="${esc(v.id)}"><span class="vehicle-thumb"></span><span><strong>${esc(v.plate)}</strong><small>${esc([v.brand,v.model].filter(Boolean).join(' '))}</small><small>${v.last_service_date?`Último servicio ${fmtDate(v.last_service_date)}`:'Sin servicios registrados'}</small></span><span class="chevron">${icon('chevron-right')}</span></button>`).join('')}
async function selectVehicle(id){const loading=UI.notify('Cargando vehículo...','loading');try{state.vehicle=await api(`/api/client/vehicles/${encodeURIComponent(id)}`);state.services=[];renderVehicle();showView('vehicle')}finally{loading.close()}}
function renderVehicle(){const v=state.vehicle.vehicle,s=state.vehicle.latest_service;$('#vehicle-meta').innerHTML=`<div><strong>${esc(v.plate)}</strong><small>Patente</small></div><div><strong>${esc(v.year||'—')}</strong><small>Año</small></div><div><strong>${km(v.current_mileage)}</strong><small>Kilometraje</small></div>`;$('#service-status').innerHTML=`<article class="status-card glass-card"><h3>${icon('oil-can')} Último servicio</h3><strong>${s?fmtDate(s.service_date):'Sin registro'}</strong><span class="muted">${s?km(s.mileage):'—'}</span></article><article class="status-card glass-card"><h3>${icon('wrench')} Próximo cambio</h3><strong>${s?.next_change_km?km(s.next_change_km):'Sin definir'}</strong><span class="muted">Según el último servicio</span></article>`;$('#personal-card').innerHTML=`<h3>${icon('user')} Datos personales</h3><strong>${esc(state.vehicle.client.full_name)}</strong><p class="muted">${esc(state.vehicle.client.phone)}</p>`}
async function loadHistory(){const loading=UI.notify('Cargando historial...','loading');try{state.services=await api(`/api/client/vehicles/${encodeURIComponent(state.vehicle.vehicle.id)}/services`);const h=$('#history-list');h.innerHTML=state.services.length?state.services.map((s,i)=>`<article class="timeline-item glass-card"><div class="row-between"><h3>${fmtDate(s.service_date)}</h3><button class="link-button" data-service-index="${i}">Ver detalle</button></div><p>${km(s.mileage)}</p><p>${s.oil?`Aceite: ${esc(s.oil)}`:'Aceite sin detalle'}</p><p>${s.next_change_km?`Próximo cambio: ${km(s.next_change_km)}`:'Próximo cambio no indicado'}</p></article>`).join(''):`<div class="notice">${icon('circle-info')} Todavía no hay servicios registrados.</div>`}finally{loading.close()}}
function renderServiceDetail(s){if(!s){$('#service-detail').innerHTML=`<div class="notice">${icon('circle-info')} No hay un servicio registrado.</div>`;return}const f=[['Fecha',fmtDate(s.service_date)],['Kilómetros',km(s.mileage)],['Próximo cambio km',km(s.next_change_km)],['Aceite',s.oil],['Tipo',s.oil_type],['Filtro de aceite',s.oil_filter],['Filtro de combustible',s.fuel_filter],['Filtro de aire',s.air_filter],['Filtro de cabina',s.cabin_filter],['Bujías',s.spark_plugs],['Aceite caja de vel.',s.gearbox_oil],['Aceite diferencial',s.differential_oil],['Engrase',s.grease],['Líquido hidráulico',s.hydraulic_fluid],['Líquido refrigerante',s.coolant],['Líquido de freno',s.brake_fluid],['Control de neumáticos',s.tire_control],['Rotación de neumáticos',s.tire_rotation],['Batería',s.battery],['Observaciones',s.observations]];$('#service-detail').innerHTML=`<article class="detail-list glass-card">${f.filter(([,v])=>v!==null&&v!==undefined&&v!==''&&v!=='—').map(([l,v])=>`<div class="detail-row"><span>${esc(l)}</span><strong>${l==='Fecha'||l.includes('Kilómetros')||l.includes('km')?v:esc(v)}</strong></div>`).join('')}</article>`}
async function loadMessages(){const loading=UI.notify('Actualizando mensajes...','loading');try{const ms=await api('/api/client/messages');$('#message-badge').textContent=ms.filter(m=>!m.is_read).length;$('#message-list').innerHTML=ms.length?ms.map(m=>`<article class="message-card glass-card ${m.is_read?'':'unread'}" data-message-id="${esc(m.id)}"><span class="message-icon">${m.message_type==='promotion'?icon('tag'):m.message_type==='reminder'?icon('bell'):icon('comments')}</span><div><span class="message-tag">${esc(m.message_type)}</span><h3>${esc(m.title)}</h3><p>${esc(m.body)}</p><small class="muted">${fmtDateTime(m.created_at)}</small></div></article>`).join(''):`<div class="notice">${icon('circle-info')} No tenés mensajes por el momento.</div>`}finally{loading.close()}}
async function enablePush(){const b=$('#enable-push');UI.setBusy(b,true,'Activando...');try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Este navegador no admite Web Push');const c=await api('/api/client/push/config');if(!c.enabled||!c.public_key)throw new Error('Web Push todavía no está configurado');if(await Notification.requestPermission()!=='granted')throw new Error('Permiso no concedido');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(c.public_key)});const j=sub.toJSON();await api('/api/client/push/subscription',{method:'POST',body:JSON.stringify({endpoint:j.endpoint,p256dh:j.keys.p256dh,auth:j.keys.auth})});b.innerHTML=`${icon('circle-check')} Activadas`;b.disabled=true;UI.notify('Notificaciones VERA activadas.','success')}catch(e){UI.notify(e.message,'error',{title:'No se pudieron activar las notificaciones'})}finally{if(!b.disabled)UI.setBusy(b,false)}}
function urlBase64ToUint8Array(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b);return Uint8Array.from([...r].map(c=>c.charCodeAt(0)))}
$('#client-login-form').addEventListener('submit',async e=>{e.preventDefault();$('#client-login-error').textContent='';const b=e.submitter;UI.setBusy(b,true,'Ingresando...');try{await api('/api/client/login',{method:'POST',body:JSON.stringify({pin:$('#client-pin').value})});await loadMe();UI.notify('Acceso correcto.','success');showMain()}catch(x){$('#client-login-error').textContent=x.message;UI.notify(x.message,'error',{title:'No se pudo ingresar'})}finally{UI.setBusy(b,false)}});
$('#forgot-pin').addEventListener('click',()=>$('#pin-help').classList.toggle('hidden'));$('#client-logout').addEventListener('click',async()=>{try{await api('/api/client/logout',{method:'POST'})}catch{}state.me=null;state.vehicle=null;showLogin()});$('#enable-push').addEventListener('click',enablePush);
document.addEventListener('click',async e=>{const v=e.target.closest('[data-vehicle-id]');if(v){try{await selectVehicle(v.dataset.vehicleId)}catch(x){UI.notify(x.message,'error')}return}const s=e.target.closest('[data-service-index]');if(s){renderServiceDetail(state.services[Number(s.dataset.serviceIndex)]);showView('detail');return}const m=e.target.closest('[data-message-id]');if(m&&m.classList.contains('unread')){try{await api(`/api/client/messages/${m.dataset.messageId}/read`,{method:'POST'});m.classList.remove('unread')}catch{}}const n=e.target.closest('[data-go]');if(!n)return;const target=n.dataset.go;if(target==='history')try{await loadHistory()}catch(x){UI.notify(x.message,'error')}if(target==='detail'){if(!state.services.length&&state.vehicle)try{await loadHistory()}catch{}renderServiceDetail(state.services[0]||state.vehicle?.latest_service)}if(target==='messages')try{await loadMessages()}catch(x){UI.notify(x.message,'error')}showView(target)});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('#install-button').hidden=false});$('#install-button').addEventListener('click',async()=>{if(!state.deferredInstall)return;await state.deferredInstall.prompt();state.deferredInstall=null;$('#install-button').hidden=true});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>UI.notify('No se pudo registrar el modo PWA.','warning')));
(async()=>{try{await loadMe();showMain()}catch{showLogin()}})();
